---
- name: Converge
  hosts: all
  #become: true
  #become_method: su
  vars:
    galaxy_commit_id: release_21.01
    galaxy_create_user: yes
    galaxy_manage_paths: yes
    galaxy_manage_clone: yes
    galaxy_manage_download: no
    galaxy_manage_existing: no
    galaxy_manage_systemd: yes
    # role default is < 22.05
    galaxy_manage_gravity: "{{ false if __galaxy_major_version is version('22.01', '<') else true }}"
    galaxy_systemd_mode: "{{ 'mule' if __galaxy_major_version is version('22.01', '<') else 'gravity' }}"
    galaxy_config_style: yaml
    galaxy_layout: root-dir
    galaxy_root: /srv/galaxy
    galaxy_separate_privileges: yes
    galaxy_user: galaxy
    galaxy_group: galaxy
    galaxy_privsep_user: gxpriv
    galaxy_config:
      galaxy:
        database_connection: sqlite:///{{ galaxy_mutable_data_dir }}/universe.sqlite
        conda_auto_init: false
    pip_virtualenv_command: /usr/bin/python3 -m venv
  pre_tasks:
    - debug:
        var: pip_virtualenv_command
    - pip:
        name: pip
        virtualenv: /tmp/test
        virtualenv_command: "{{ pip_virtualenv_command }}"
    - name: Install dependencies (yum)
      yum:
        name: [sudo, git, make, bzip2]
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8", "<")
  roles:
    - role: galaxyproject.galaxy
