---
name: Molecule Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  molecule:
    name: molecule
    # systemd may not work under 22.04 due to cgroupsv2
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scenario:
          - default
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install molecule[docker] ansible-core

      - name: Run molecule
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_STDOUT_CALLBACK: yaml
